---
- name: Install and configure nginx
  ansible.builtin.include_role:
    name: geerlingguy.nginx
- name: Add custom nginx load balancer config
  ansible.builtin.template:
    src: custom_loadbalancer.conf.j2
    dest: /etc/nginx/conf.d/custom_loadbalancer.conf
    mode: "0644"
  notify:
    - Restart nginx
